version: '3'

services:
  web:
    image: nginx:1.27
    ports:
      - "80:80"
    volumes:
      - ./app/config/etc/nginx/dev/conf.d:/etc/nginx/conf.d
      - ./frontend/public:/var/www/public
    depends_on:
      - backend
    networks:
      - frontend    
      - backend
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - frontend    
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
    networks:
      - backend
  db:
networks:
  frontend:
  backend:
